language: ruby
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mysql -e 'create database cojiro_test;'
script: "bundle exec rake travis"
rvm:
  - 1.9.2
  - 1.9.3
env:
  - CI=true
bundler_args: --without development
branches:
  only:
    - develop
    - master
